config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :articles
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one_attached :document

  validates :title, :description, :price, presence: true

  default_scope { order(id: :desc) }

  # `broadcast_replace_later_to` and `broadcast_prepend_later_to` methods send the msg asyncroniously as compared to `broadcast_prepend_to` and `broadcast_replace_to`
  after_create_commit -> { broadcast_prepend_later_to "articles", partial: "articles/article", locals: { article: self }, target: "articles" }
  after_update_commit -> { broadcast_replace_later_to "articles", partial: "articles/article", locals: { article: self } } # DEFAULT target is model.plural which is definately the case here
  after_destroy_commit -> { broadcast_remove_to "articles" }

  # synthatic sugar syn tax for the above 3 lines in 1 line
  # broadcasts_to ->(quote) { "quotes" }, inserts_by: :prepend
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = "Article was successfully updated." }
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      respond_to do |format|
        format.html { redirect_to article_path(@article), notice: "Article was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Article was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }
    end
  end
 
  private

  def article_params
    params.require(:article).permit(
      :title,
      :description,
      :document,
      :price,
    )
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<%= turbo_frame_tag dom_id(article) do %>
<div class="container p-3 m-3 bg-white rounded align-middle">
  <div class="row">
    <div class="col-10">
      <%= link_to article.title,
        article_path(article),
        class: "align-middle link-offset-2 link-underline link-underline-opacity-0",
        data: { turbo_frame: "_top" }
      %>
    </div>
    <div class="col-1">
      <%= link_to article_path(article),
        method: :delete,
        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
        class: "text-danger float-end" do %>
          <i class="fa-solid fa-trash" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class="col-1">
      <%= link_to edit_article_path(article),
        class: "text-info" do %>
          <i class="fas fa-edit" aria-hidden="true"></i>
    <% end %>
  </div>

  </div>
</div>
<% end %>

app/views/articles/create.turbo_stream.erb
<%= turbo_stream.prepend "articles", partial: "articles/article", locals: { article: @article } %>
<%= turbo_stream.update Article.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/articles/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@article) %>
<%= render_turbo_stream_flash_messages %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= turbo_frame_tag dom_id(@article) do %>
  <%= form_with(model: @article) do |form| %>
    <% if @article.errors.any? %>
      <div id="error_explanation" class="text-danger" >
        <p><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title, "Title", class: "form-label" %>
      <%= form.text_field :title, class: "form-control", id: "title_id", aria: { describedby: "emailHelp" } %>
    </div>

    <div class="form-group">
      <%= form.label :description, "Description", class: "form-label" %>
      <%= form.text_field :description, class: "form-control", id: "description_id", aria: { describedby: "emailHelp" } %>
    </div>

    <div class="form-group">
      <%= form.label :document, "Document", class: "form-label" %>
      <%= form.file_field :document, class: "form-control", id: "description_id", aria: { describedby: "emailHelp" } %>
    </div>


    <div class="form-group">
      <%= form.label :price, "Price", class: "form-label" %>
      <%= form.text_field :price, class: "form-control", id: "price_id" %>
    </div>

    <button type="submit" class="btn btn-primary mt-2 float-end">Update Article</button>
    <br>
    <br>
  <% end %>
<% end %>

app/views/articles/index.html.erb
<%= turbo_stream_from "articles" %>

<h2>Articles</h2>
<p>The list of all the articles </p>

<%= link_to 'New Article',
  new_article_path,
  class: "btn btn-primary float-end",
  data: { turbo_frame: dom_id(Article.new) }
%>

<br>

<%= turbo_frame_tag dom_id(Article.new) do %>
<% end %>

<br>
<%= turbo_frame_tag "articles" do %>
  <%= render @articles %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= turbo_frame_tag dom_id(Article.new) do %>  
  <%= form_with(model: @article, local: true) do |form| %>
    <% if @article.errors.any? %>
      <div id="error_explanation text-danger">
        <p><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title, "Title", class: "form-label" %>
      <%= form.text_field :title, class: "form-control", id: "title_id", aria: { describedby: "emailHelp" } %>
    </div>

    <div class="form-group">
      <%= form.label :description, "Description", class: "form-label" %>
      <%= form.text_field :description, class: "form-control", id: "description_id", aria: { describedby: "emailHelp" } %>
    </div>

    <div class="form-group">
      <%= form.label :document, "Document", class: "form-label" %>
      <%= form.file_field :document, class: "form-control", id: "description_id", aria: { describedby: "emailHelp" } %>
    </div>


    <div class="form-group">
      <%= form.label :price, "Price", class: "form-label" %>
      <%= form.text_field :price, class: "form-control", id: "price_id" %>
    </div>

    <button type="submit" class="btn btn-primary mt-2 float-end">Create Article</button> <br>
  <% end %>
<% end %>

app/views/articles/show.html.erb
<h2>
Article Show
</h2>

<div class="row">
  <div class="col-9">
    <h5>
      <%= @article.title %>
    </h5>
    <p>
      <%= @article.description %>
    </p>
    <br>
    <p class="fw-bold">
      Created by: <%= @article.user.email %>
    </p>
  </div>
  <div class="col-3">
      <button type="button" class="btn btn-info">Purchase</button>
  </div>
  <div>
    <% if @article.document.attached? %>
      Downloadable Link: <%= link_to @article.document.filename.to_s, rails_blob_path(@article.document, disposition: "attachment") %>
    <% else %>
      No document available
    <% end %>

    <% if @article.document.previewable? %>
      <%= image_tag @article.document.preview(resize_to_limit: [800, 800]).processed, class: "img-fluid" %>
    
    <% elsif @article.document.image? %>
      <%= image_tag @article.document, class: "img-fluid" %>
    
    <% elsif @article.document.content_type == "application/pdf" %>
      <embed src="<%= url_for(@article.document) %>" type="application/pdf" width="100%" height="600px" />
    
    <% else %>
      <p> This document cannot be previewed. You can <%= link_to "download it", rails_blob_path(@article.document, disposition: "attachment") %>.</p>
    <% end %>
    <br>
    <br>
  </div>
</div>

app/views/articles/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@article), partial: "articles/article", locals: { article: @article } %>
<%= render_turbo_stream_flash_messages %>